version: '2'
services:
  discoveryserver:
    image: jppm/discovery-service:latest
    ports:
      - "8761:8761"
  database:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=p0stgr@s
     - POSTGRES_DB=jppm
#  Alternative DB
#    image: mariadb:latest
#    restart: always
#    ports:
#     - 3306:3306
#    environment:
#     - MYSQL_ROOT_PASSWORD=pass
#     - MYSQL_DATABASE=jppm
#     - MYSQL_USER=user
#     - MYSQL_PASSWORD=pass
#    volumes:
#     - ./database:/var/lib/mysql
  propertyservice:
    image: jppm/property-service:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      DISCOVERYSERVER_URI:  "http://discoveryserver:8761/eureka/"
      DATABASESERVER_PORT:  "5432"
#  Alternative DB port
#      DATABASESERVER_PORT:  "3306"
      DISCOVERYSERVER_PORT: "8761"
  key-value:
    image: redis:alpine
    ports:
      - "6379:6379"
  gatewayservice:
    image: jppm/gateway-service:latest
    ports:
      - "8090:8090"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8090"
      PROPERTYSERVICE_PORT: "8080"
      REDISSERVER_PORT: "6379"
      DISCOVERYSERVER_URI:  "http://discoveryserver:8761/eureka/"
      DISCOVERYSERVER_PORT: "8761"